#! python3
# A Shebang indicates which Bash or Python interpreter to use to interpret an executable file. 
# https://app.datacamp.com/learn/tutorials/python-excel-tutorial
import sys, webbrowser, re, time , os
from pathlib import Path
# add a day to a date field
from datetime import datetime, timedelta, date
import openpyxl


inputPath = "C:/Users/ben/OneDrive/Documents/Gaba_Docs/Whisperer/FBRef/2025 Files/AllDomesticLeagues/"
inputFile = "Fbref_20250102"   + ".xlsx"

outputPath = "C:/Users/ben/OneDrive/Documents/Gaba_Docs/development/Python/Python_Ben/pgmOutput/"
outputFile = "WSB_20250102a" + ".xlsx"

iterate =[]
iterate.append('one')

for ite in iterate:

    try:
        # Load workbook
        wb = openpyxl.load_workbook(inputPath+inputFile)

        # Select active sheet
        # sheet = wb.active

        # Select specific sheet 
        ws = wb['Fbref_Teams']

        # count the number of rows and columns in this worksheet
        print('Total number of rows: '+str(ws.max_row)+'. And total number of columns: '+str(ws.max_column))

        # Access cell values / retrieve data from a specific cell 
        cell_value = ws['B2'].value

        # AVERAGE
        ws['AC1'] = 'Average Points'
        ws['AC2'] = '= AVERAGE(J2:{0})'.format("J"+str(ws.max_row))

        # COUNTA
        # The “COUNTA” function in Excel counts cells that are populated within a specific range
        ws['AD1'] = "Number of Populated Cells" 
        ws['AD2'] = '=COUNTA(AC2:{0})'.format("AC"+str(ws.max_row))

        # COUNTIF
        # counts the number of cells that meet a specific condition. 
        # za Premier Division (2 teams) or it Serie A (3 Teams)
        ws['AE1'] = 'Number of Rows with Competition/League Name'
        ws['AE2'] = '=COUNTIF(D2:{}, "za Premier Division")'.format("D"+str(ws.max_row))

        # SUMIF
        # SUM the number of cells that meet a specific condition.
        ws['AF1'] = 'Sum Rows with Competition/League Name'
        ws['AF2'] = '=SUMIF(D2:{}, "za Premier Division",J2:{})'.format("D"+str(ws.max_row),"J"+str(ws.max_row))

        # CEILING
        # rounds a number up to the Next Nearest (UP) specified multiple (25). Let’s round up the total amount of points generated by Competition/League Name using this function:
        ws['AG1'] = 'Rounded Sum of mpetition/League Name'
        ws['AG2'] = '=CEILING(AF2,25)'

    except Exception as e:
        print("could not open input file..: " + inputPath+inputFile+'\n' + inputPath + '\n' + inputFile + '\n' +str(e))

wb.save(inputPath+inputFile)
wb.close()
exit